# Generated by Django 3.0.6 on 2020-06-29 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('BoardID', models.AutoField(primary_key=True, serialize=False)),
                ('board_title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostID', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=64)),
                ('post_time', models.DateTimeField(auto_now=True)),
                ('post_text', models.CharField(max_length=1024)),
                ('Board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.Board')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=24)),
                ('user_name', models.CharField(max_length=32)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=128)),
                ('user_avatar', models.ImageField(upload_to='')),
                ('user_signature', models.CharField(max_length=512)),
                ('user_is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('ReplyID', models.AutoField(primary_key=True, serialize=False)),
                ('reply_time', models.DateTimeField(auto_now=True)),
                ('reply_text', models.CharField(max_length=1024)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.Post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.User'),
        ),
        migrations.AddField(
            model_name='board',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.Category'),
        ),
    ]
