# Generated by Django 3.0.6 on 2020-06-29 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentID', models.AutoField(primary_key=True, serialize=False)),
                ('comment_time', models.DateTimeField(auto_now=True)),
                ('comment_text', models.CharField(max_length=1024)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.Post')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumapp.User'),
        ),
    ]
