# Generated by Django 3.0.6 on 2020-07-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_auto_20200628_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_department',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
